# Generated by Django 2.1.7 on 2019-07-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_invigilatorresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examvenue',
            name='examname',
        ),
        migrations.RemoveField(
            model_name='examvenue',
            name='roomname',
        ),
    ]
