# Generated by Django 2.1.7 on 2019-07-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190711_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilatorresponse',
            name='assigned_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.ExamVenue'),
        ),
    ]
