# Generated by Django 2.1.7 on 2019-07-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_invigilatorresponse_assigned_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilatorresponse',
            name='assigned_venue',
            field=models.ForeignKey(limit_choices_to={'exam': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.ExamVenue'),
        ),
    ]
