# Generated by Django 2.1.7 on 2019-07-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190711_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilatorresponse',
            name='assigned_venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.ExamVenue'),
        ),
    ]
